### ISSUE TITLE
Watch out for spammers

### ISSUE THREAD

**Issue by DibranMulder** [madskristensen/PhotoGallery#5]
I'm able to upload images on your demo website since you provide the username and password in the read me. I'm ethical I don't upload nasty stuff but there might be people who might. 

https://gallerytemplate.azurewebsites.net/photo/nature/yoda/

**Comment by madskristensen** [comment]
Yeah, I thought about that. I like the idea of letting people log in so they can try out all the features. I've done that with another project of mine (MiniBlog) and I've never had any complaints. It is a real concern though, but I think I'm gonna continue letting people log in and when/if it becomes a problem I'll disallow logging in.
